sadoprotocol/ordit-sdk

packages/sdk/src/transactions/psbt.ts

This PR updates a typo to the correct spelling.

fix(sdk): update typo in addInputToPsbtByType fn

---

.github/PULL_REQUEST_TEMPLATE.md
.github/oss-governance-bot.yml
.github/oss-governance-labeler.yml
.github/oss-governance-labels.yml
.github/release-drafter.yml
.github/renovate.json
.github/workflows/ci.yml
.github/workflows/governance.yml
.github/workflows/labeler.yml
.github/workflows/labels.yml
.github/workflows/publish.yml
.github/workflows/release-drafter.yml
packages/sdk/src/utils/index.ts

Changes:
1. Add PR Template
2. Release drafter for easier changelog
3. Renovate
4. CI builds - Lint and build for PRs

feature(ops): setup renovate, CI builds

---

packages/sdk/src/api/index.ts

This PR consolidates multiple metadata decode implementations into one reusable class function. Also, removes unused class members and constructor from `OrditApi` class.

refactor(sdk): create reusable fn to transform inscriptions

---

packages/sdk/src/inscription/instant-buy.ts

This PR refactors the `generateRefundableUTXOs` method to generate 2 UTXOs worth 600 sats and remaining sats as change. The idea is to generate utxos w/ minimum sats that can be used as refundable UTXOs for the instant buy & sell process. 
Current implementation of equally splitting the UTXOs is proving to be a blocker for users w/ just one UTXO -- resulting in insufficient balance as the actual UTXO to be used to cover for the sell price + network fees is not enough.

refactor(sdk)!: create 2 refundable utxos worth 600 sats each

---

packages/sdk/src/browser-wallets/unisat/signatures.ts

This PR updates the response format for Unisat signer wrapper to comply w/ the similar change made for Xverse in [#50](https://github.com/sadoprotocol/ordit-sdk/pull/50/files#diff-ec81a4f73ebe571601fbaa6504c4a56be60929d703bb7be8898b125f99f670d6R9-R56). 
Also, unncessary try..catch block has been removed.

refactor(sdk): update response format for Unisat signer

---

packages/sdk/src/inscription/witness.ts

This PR reverts the default chunking implementation in `opPush`. The idea is to keep `opPush` atomic and simpler. If the data exceeds 520 bytes in size, `opPush` will throw an error stating to chunk the data before attempting to push it.

revert(sdk): chunk by default in `opPush`

---

packages/sdk/src/instant-trade/InstantTradeBuilder.ts
packages/sdk/src/instant-trade/InstantTradeBuyerTxBuilder.ts
packages/sdk/src/instant-trade/InstantTradeSellerTxBuilder.ts
packages/sdk/src/transactions/PSBTBuilder.ts

This PR updates the `royalty` object structure to include `percentage` and `receiver` address.

refactor(sdk): update royalty structure

---

packages/sdk/src/browser-wallets/xverse/signatures.ts

previously the function return type was inferred causing the response to be always `null`
Fixes #

feat(sdk): add function typing to xverse signMessage

---

packages/sdk/src/fee/FeeEstimator.ts
packages/sdk/src/inscription/collection.ts
packages/sdk/src/inscription/witness.ts
packages/sdk/src/instant-trade/InstantTradeBuilder.ts
packages/sdk/src/instant-trade/InstantTradeBuyerTxBuilder.ts
packages/sdk/src/instant-trade/InstantTradeSellerTxBuilder.ts
packages/sdk/src/modules/JsonRpcDatasource.ts
packages/sdk/src/signatures/message.ts
packages/sdk/src/signatures/psbt.ts
packages/sdk/src/transactions/Inscriber.ts
packages/sdk/src/transactions/PSBTBuilder.ts
packages/sdk/src/transactions/psbt.ts
packages/sdk/src/utils/errors.ts
packages/sdk/src/utils/index.ts
packages/sdk/src/utxos/UTXOManager.ts
packages/sdk/src/wallet/Ordit.ts

feat(sdk): add custom OrditSDKError class

---

packages/sdk/src/transactions/Inscriber.ts

feat(sdk): ensure that in recovery mode, there is only 1 output

---

packages/sdk/src/constants/index.ts

feat(sdk): Increase network fee limit to 5 BTC

---

package.json
packages/sdk/package.json
pnpm-lock.yaml

bump(packages): use caret for packages' version, update to latest

---

packages/sdk/src/constants/index.ts
packages/sdk/src/instant-trade/InstantTradeBuilder.ts
packages/sdk/src/instant-trade/InstantTradeBuyerTxBuilder.ts

Adding a general `outputs` field to instant trade buyer builder to cater for any upcoming fees
Fixes #

feat(fee): add instant trade buyer to accept general outputs

---

packages/sdk/src/transactions/Inscriber.ts

fix(inscriber): accept and pass down datasource in inscriber

---

packages/sdk/src/addresses/formats.ts
packages/sdk/src/api/jsonrpc.ts
packages/sdk/src/config/index.ts
packages/sdk/src/config/types.ts
packages/sdk/src/utils/index.ts

feat(sdk): support signet

---

packages/sdk/src/instant-trade/InstantTradeSellerTxBuilder.ts

allow royalty to be injected in constructor
Fixes #

feat(sdk): add the ability to inject royalty

---

packages/sdk/src/inscription/collection.ts
packages/sdk/src/transactions/Inscriber.ts
packages/sdk/src/transactions/types.ts

feat(sdk): add taproot tree version for backward compatibility

---

packages/sdk/src/addresses/index.ts
packages/sdk/src/wallet/Ordit.ts
packages/sdk/src/wallet/index.ts

Allows to set account and wallet address. Modified wallet initialization and `setDefaultAddress`
Fixes #

chore(wallet): allow to specify custom account and index

---

packages/sdk/src/inscription/collection.ts
packages/sdk/src/inscription/encoding.ts
packages/sdk/src/inscription/witness.ts
packages/sdk/src/transactions/InscriberV2.ts
packages/sdk/src/utils/index.ts

Support delegates for `InscriberV2` class + small fixes 
Fixes #

feat(inscriberV2): support delegates

---

packages/sdk/src/utils/index.ts

should return `p2wsh` instead of `p2wpkh`
Fixes #

fix(sdk): return p2wsh

---

packages/sdk/src/transactions/types.ts

chore(spendable): add confirmation on UTXOLimited
