sadoprotocol/ordit-sdk

- examples/node/README.md
- examples/node/package.json
- examples/node/send.js
- packages/sdk/src/addresses/index.ts
- packages/sdk/src/transactions/relay.ts
- packages/sdk/src/wallet/Ordit.ts
- packages/sdk/src/wallet/index.ts
- packages/sdk/tsconfig.build.json
- packages/sdk/tsconfig.json
1. Fix `utxo/unspents` API call bug where the address is incorrectly passed into the payload
2. Enable source map for ease of debugging by developers
3. Directy return `txId` for the `utxo/relay` endpoint
4. Introduce `getAddressType` for the inverse derivation of an address format type
5. Add `send` example (send safe to spend sats, i.e. cardinals)
> refactor: multiple improvements & bug fixes

- packages/sdk/src/addresses/index.ts
- packages/sdk/src/utils/index.ts
- packages/sdk/src/wallet/Ordit.ts
This PR refactors the way new addresses are generated by relying on explicitly provided path levels.
1. Renamed `addAddress`  to `generateAddress`
2. Extended `generateAddress` to generate new address based on the following provided path levels:
- `account`
- `addressIndex`
4. Add types
Breaking change: 
- `generateAddress` bypasses the `allAddresses` store on the `Ordit` class -- meaning newly generated addresses are not tracked which at this point may break recently introduced instant-buy feature.
> refactor!: update getAddress to generate new address based on provided path levels

- packages/sdk/src/api/index.ts
This PR adds the missing optional `meta` property to `InscriptionsEntity` interface.
As per [OIP-1](https://github.com/sadoprotocol/oips/blob/main/oip-01-inscription-metadata.md), the `meta` object is returned by the [utxo/unspents](https://github.com/sadoprotocol/utxo-api/blob/a2cb353a1ef80c77307af2915b8b10d195d4c144/src/lookup.js#L126-L143) endpoint.
> fix(sdk): add missing meta property to inscription object

- packages/sdk/src/browser-wallets/xverse/signatures.ts
`xverse/signatures/signPsbt` returns the wrong type.
It returns `Promise<null>` when it should return:
```
Promise<{
rawTxHex: string,
psbt: {
hex: string,
base64: string
}
}>
```
This PR will initialise the return object as an empty template that corresponds to the newly added `XverseSignedPsbt` interface, instead of just null. This allows TypeScript to infer the return type correctly.
Fixes #5
> fix(sdk/xverse): return a defined type for signPsbt fn

- packages/sdk/src/transactions/psbt.ts
`spendables` can be `undefined` when the wallet has no cardinals
https://github.com/sadoprotocol/ordit-sdk/blob/6f0391bca8bbb25c705c24213ad929ad682b8dc5/packages/sdk/src/transactions/psbt.ts#L47
`Error: Cannot read properties of undefined (reading 'forEach')`
This fix checks if `spendables` is defined before attempting to loop through the array.
Fixes #11
> fix(sdk): handle undefined spendables

- examples/node/send.js
- packages/sdk/src/transactions/psbt.ts
Let the consumer specify a custom fee rate (sats per byte) when creating a PSBT. (Optional)
> feat(psbt): allow custom fee rate in `createPsbt`

- .prettierrc
- examples/node/collections.js
- examples/node/create-psbt.js
- examples/node/inscribe.js
- examples/node/instant-buy.js
- examples/node/package.json
- examples/node/utils.js
- packages/sdk/src/api/index.ts
- packages/sdk/src/browser-wallets/unisat/index.ts
- packages/sdk/src/browser-wallets/unisat/signatures.ts
- packages/sdk/src/browser-wallets/unisat/types.ts
- packages/sdk/src/constants/index.ts
- packages/sdk/src/inscription/commit.ts
- packages/sdk/src/inscription/instant-buy.ts
- packages/sdk/src/inscription/psbt.ts
- packages/sdk/src/transactions/OrdTransaction.ts
- packages/sdk/src/transactions/psbt.ts
- packages/sdk/src/types.d.ts
- packages/sdk/src/utils/index.ts
- packages/sdk/src/utils/types.ts
- packages/sdk/src/wallet/Ordit.ts
- packages/sdk/src/wallet/index.ts
This PR calculates the tx fees based on actual input and output bytes wrt. to the tx type (p2tr, p2wpkh, etc.). Earlier, the calculation was done on an arbitrary number of 180 that closely aligns w/ legacy input bytes. Following are the references for the hardcoded input and output bytes:
1. [bitcoinops.org](https://bitcoinops.org/en/tools/calc-size/) - tx size calculator
2. [Answer](https://bitcoin.stackexchange.com/a/87276/143085) by Pieter Wuille on bitcoin.stackenchange.com (Co-author of BIP-141)
Additionally, the following bug fixes and improvements have been tagged along w/ this PR: 
1. Disable semicolon in Prettier config
2. Lint all changed files
3. Remove intentional suppressing of error or unnecessary `try..catch` blocks
4. Add new and improvise existing code examples
5. Fix …
> refactor(sdk)!: dynamic fee calculation and improvements

- examples/node/inscribe.js
- packages/sdk/src/inscription/commit.ts
- packages/sdk/src/inscription/psbt.ts
- packages/sdk/src/transactions/OrdTransaction.ts
- packages/sdk/src/utils/index.ts
- packages/sdk/src/utils/types.ts
This PR fixes the issue of inscription tx failure by encoding the values of `meta`. Properties including but not limited to `title` / `description` can potentially have non-utf8 characters and the SDK should properly encode it before inscribing it on-chain.
The package consumers are supposed to decode the `meta` object recursively on their end. [Functions from this PR](https://github.com/sadoprotocol/ordit-sdk/pull/32/files#diff-9253a4b03ec0ce7e7bb72d41d6d289076a5341c18445510ffbcb645a7adaa70cR145-R172) can be used to decode.
Also, a fix has been added to inscribe example.
> feat(sdk): encode inscription `meta` values

- packages/sdk/src/transactions/psbt.ts
This PR fixes the input generator by adding the missing `witness_v0_keyhash` type for nested segwit txs. Also, a few improvements to the input generator have been added in this PR.
- Renamed multiple argument options properties
- Removed `satsPerByte = 10` default value from args of `createPsbt` fn
- Move RBF enabling logic to higher level
> fix(sdk)!: add missing address type to input generator

- examples/node/instant-buy.js
- packages/sdk/src/inscription/instant-buy.ts
This PR updates the response type of `generateSellerPsbt` and `generateBuyerPsbt` functions.
> refactor(sdk): update response type of generate buyer and seller psbt

- examples/node/create-psbt.js
- examples/node/instant-buy.js
- packages/sdk/src/api/index.ts
- packages/sdk/src/api/types.ts
- packages/sdk/src/browser-wallets/unisat/signatures.ts
- packages/sdk/src/browser-wallets/unisat/types.ts
- packages/sdk/src/browser-wallets/xverse/signatures.ts
- packages/sdk/src/inscription/collection.ts
- packages/sdk/src/inscription/instant-buy.ts
- packages/sdk/src/inscription/psbt.ts
- packages/sdk/src/transactions/OrdTransaction.ts
- packages/sdk/src/transactions/types.ts
- packages/sdk/src/utils/index.ts
This PR adds multiple improvements, refactors, and fixes. Following are the changes:
1. Replace `GetUnspents` w/ `GetSpendables` API to improve performance wherever the final value is known
2. Add util method to convert Satoshis to BTC and vice-versa
3. Add `sort` option to `GetUnspents` API
4. Add postage amount to total input amount calculation in instant buy-sell flow
5. Add API to get balance for address
6. Extend Unisat and Xverse signature wrapper to accept `finalize` and `extractTx` options
7. Fixed message format for verifiable ordinals per OIP-2 standards
> refactor(sdk): integrate `GetSpendables` API & improvements

- packages/sdk/src/utils/index.ts
- packages/sdk/src/utils/types.ts
This PR adds util methods to decode various formats of PSBT and Tx to finally convert it into a JS native relevant class instance. Following are the supported formats:
- PSBT
- Buffer
- Base64
- Hex
- Transaction
- Buffer
- Hex
> feat(sdk): add util methods to decode PSBT and tx

- packages/sdk/src/inscription/instant-buy.ts
- packages/sdk/src/transactions/OrdTransaction.ts
This PR allows higher value UTXO that could potentially be sent by mistake to the commit address. The idea is to return the change if its above the dust value (600 sats), if the difference is less than dust value -- it will be spent as fees.
Also, an issue where instead of addition, parsing was being done has been fixed. Postage, and sell price are now part of the `generateBuyerPsbt` method response.
> fix(sdk): allow higher value utxos and return change

- packages/sdk/src/transactions/OrdTransaction.ts
This PR fixes the incorrect comparison of BTC value w/ sats value.
> fix(sdk): compare with sats value instead of BTC value

- packages/sdk/src/api/jsonrpc.ts
- packages/sdk/src/inscription/collection.ts
- packages/sdk/src/transactions/OrdTransaction.ts
- packages/sdk/src/transactions/psbt.ts
This PR has the following changes:
1. Extended publish collection and mint asset functions to accept `enableRBF` flag
2. Extended `OrdTransaction` class to accept `enableRBF` flag
3. Return detailed error message for clarity on errors returned by RPC
4. Remove extra RPC call and use existing data
> refactor(sdk): performance improvements

- packages/sdk/src/transactions/OrdTransaction.ts
This PR fixes the fee issue for Taproot txs specifically in the inscription, and funds recovery flow. The root cause of the issue is that during fee calculation, the raw witness script was used to calculate the fee whereas the correct way to do that is to send the raw witness to payments API of bitcoinjs-lib `bitcoin.payments.[p2tr|p2sh|etc]` and access the `witness` property of the response.
The accuracy is not 100% but still better than the previous 8% miscalculation. Now, its off by 0.33%.
Custom fee rate: 3 sats/vByte
Prev implementation: 2.76; [inscription tx](https://mempool.space/testnet/tx/edaf7356b1a0ec9b7672bc74a86635c5a095e9a9911f0f6f1450848f0a52b429)
Now: 2.99; [inscription tx](https://mempool.space/testnet/tx/99a5e2ecd3a550245b03d7acf91003e6563ee49cdd0e07e7a738ce66efff504f) …
> fix(sdk): use dynamic witness generated by payments API to calculate fee

- packages/sdk/src/browser-wallets/types.ts
- packages/sdk/src/browser-wallets/xverse/signatures.ts
- packages/sdk/src/config/index.ts
- packages/sdk/src/inscription/instant-buy.ts
- packages/sdk/src/inscription/types.ts
- packages/sdk/src/transactions/OrdTransaction.ts
- packages/sdk/src/wallet/Ordit.ts
This PR updates all relevant ordit-sdk fns that builds a PSBT to return signing data to support XVerse wallet fns. Input indexes to sign w/ corresponding `address`, and an optional `sigHash` will be returned by ordit-sdk fns.
> refactor(sdk): retrieve signing data for XVerse wallet functions

- packages/sdk/src/browser-wallets/xverse/signatures.ts
This PR fixes the Xverse signer wrapper by finalizing only the inputs explicitly passed wrt. indexes passed. In the instant-buy-sell flow inputs belonging to multi parties are merged into a single PSBT and the party broadcasting the final tx is supposed to ensure all inputs are finalized. 
Changes in this PR only finalizes the inputs that are explicitly asked to finalize instead of the current implementation that finalizes all inputs.
> fix(sdk-xverse): finalize specific inputs when passed explicitly

- packages/sdk/src/transactions/OrdTransaction.ts
This PR adds a flag to bypass the strict sats check in inscription builder class. Many txs that were initiated by users earlier are now stuck because of the recent release that updated the fee calculation.
If fee is changed, the reveal fee is changed too and the inscription builder would not pass the check because the sats/value of original UTXO by user to the commit address would be different.
> feat(sdk): add flag to skip strict sats check

- examples/node/collections.js
- packages/sdk/src/fee/FeeEstimator.ts
- packages/sdk/src/inscription/collection.ts
- packages/sdk/src/instant-trade/InstantTradeBuilder.ts
- packages/sdk/src/instant-trade/InstantTradeBuyerTxBuilder.ts
- packages/sdk/src/instant-trade/InstantTradeSellerTxBuilder.ts
- packages/sdk/src/transactions/Inscriber.ts
- packages/sdk/src/transactions/PSBTBuilder.ts
This PR introduces a new feature called **Royalty** as defined in [OIP-6](https://www.oips.io/oip-06-ordinals-royalty-standard). This new feature would enable new collections created by artists/creators to receive a royalty payment on each trade. Participating marketplaces should follow OIP-6 as the guideline to enable royalty payments on their platform.
**Note**: Royalty is an optional feature and creators can opt-out at the time of collection creation.
Creators can choose royalty in % as low as 0.001% all the way up to 1000%. On every trade tx, the royalty payment would be would be calculated wrt. to the sell price. 
```
E.g., 
sell price = 200000 sats
royalty set by creator = 5%
royalty to be paid to creator = 10000 sats
```
In case the calculated royalty in sats is lower than dust or …
> feat(sdk)!: introduce royalty payments in instant-trade flow

- packages/sdk/src/api/index.ts
- packages/sdk/src/fee/FeeEstimator.ts
- packages/sdk/src/instant-trade/InstantTradeBuilder.ts
- packages/sdk/src/instant-trade/InstantTradeBuyerTxBuilder.ts
- packages/sdk/src/instant-trade/InstantTradeSellerTxBuilder.ts
- packages/sdk/src/modules/JsonRpcDatasource.ts
- packages/sdk/src/transactions/Inscriber.ts
- packages/sdk/src/transactions/PSBTBuilder.ts
- packages/sdk/src/transactions/types.ts
This PR adds validation to check ownership of the inscription in the seller flow. Also, the flag to skip strict sats introduced in #65 has been restored. 
A few fixes have also been included in the PR. Check the commits/changes to learn more.
> feat(sdk): add sats and ownership check

- examples/node/package.json
- packages/sdk/src/instant-trade/InstantTradeBuilder.ts
- packages/sdk/src/utxos/UTXOManager.ts
This PR fixes the issue where the UTXO splitter primarily used in the instant-trade flow created incorrect outputs. With the changes in this PR, the splitter fn would now create 2 outputs worth the minimum amount (600 sats).
Also, a fix to find all inscriptions to later find by outpoint has been added in this PR.
> fix(sdk): create outputs for minimum amount in utxo splitter

- packages/sdk/src/inscription/collection.ts
- packages/sdk/src/transactions/Inscriber.ts
This PR includes the change that will send the inscription to the destination address. In the funds recovery flow, the recovered funds would be sent to the change address. 
In the event where destination address or change address is missing in both the flows, the wallet/address that has initiated the request will receive the inscription, and recovered funds, respectively.
> fix(sdk): send inscription to destination address & recovered funds to change address

- packages/sdk/src/transactions/Inscriber.ts
This PR includes changes that ensures the outputs are ordered in such a way that the inscription output is always on the 0th index (first output) followed by additional outputs and change output.
> fix(sdk): update output order to ensure inscription is on 0th index

- packages/sdk/src/transactions/PSBTBuilder.ts
This PR adds `sigHash` to `inputsToSign` getter on `PSBTBuilder` class. `sigHash` has to be passed explicitly to XVerse signer despite binding it to the input.
> feat(sdk): add sigHash to inputsToSign getter

- packages/sdk/src/instant-trade/InstantTradeBuyerTxBuilder.ts
This PR includes the change that lets `PSBTBuilder` take full-control over the buyer PSBT and fetch more UTXOs as needed. However, we still check for a minimum of 3 UTXOs during the eligibility validation.
> fix(sdk): allow PSBTBuilder to fetch more UTXOs as needed

- packages/sdk/src/modules/JsonRpcDatasource.ts
This PR uses the the latest response type for `GetInscriptions` RPC. This is a temporary fix and should be standardised in #68
> fix(sdk): temporary fix for getInscriptions

- packages/sdk/src/transactions/PSBTBuilder.ts
This PR deducts already retrieved amount from the amount required to cover for the outputs, and network fee. Builder like `InstantTrader` that are built on top of `PSBTBuilder` retrieve UTXOs on their own, and let `PSBTBuilder` only fetch additional if there's a need.
Also, change output has been decoupled from `outputs` for keep a clear separation of user provided outputs and auto-calculated (change) output.
> fix(sdk): deduct already retrieved amount

- packages/sdk/src/constants/index.ts
- packages/sdk/src/inscription/witness.ts
This PR fixes a critical bug where the witness data (content/metadata) was being chunked based on the length of stringified data. Characters like `ō` or `å` are 2 bytes in size as opposed to a standard `o` or `a` and chunking the data based on the string length would generate a chunk that is greater in size than the max limit.
The solution implemented in this PR takes the string's byte level in consideration to generate chunks.
> fix(sdk): chunk witness data wrt. bytes instead of str length

- packages/sdk/src/fee/FeeEstimator.ts
This PR bumps input size by 0.5 Byte for Taproot to prevent a terminal/halting issue:
`min relay fee not met [minimum] < [fee-calculated-by-sdk]`
Usually the difference is merely 1 sat and everything comes to an halt. Despite the current sizes being correct, the issue persists. The idea of this PR is to over-estimate the fee slightly (no significant change).
> fix(sdk): bump taproot input size by 0.5B

- packages/sdk/src/constants/index.ts
- packages/sdk/src/inscription/collection.ts
- packages/sdk/src/instant-trade/InstantTradeSellerTxBuilder.ts
This PR deducts the royalty amount from seller price. So, if the seller sells an item for 100 and royalty for that item is set to 5% -- the seller would receive 95 and 5 would be sent to the creator as royalty payment.
Also, a max cap of 10% has been added. Creators can set only `royalty <= 10%`.
> feat(sdk): deduct royalty from seller price & cap to 10%

- packages/sdk/src/instant-trade/InstantTradeBuyerTxBuilder.ts
Changes in this PR exits royalty decoding for non-royalty inscriptions.
> fix(sdk): exit when royalty is not defined

- packages/sdk/src/constants/index.ts
This PR bumps the maximum royalty percentage from 10% to 20%.
> refactor(sdk): bump max royalty perc to 20

- packages/sdk/src/browser-wallets/unisat/addresses.ts
- packages/sdk/src/types.d.ts
As per docs (https://docs.unisat.io/dev/unisat-wallet-api#getaccounts) unisat got 2 methods, one is `requestAccounts` and another is `getAccounts`. They both returning same results, but request version comes with a side-effect that also opens wallet connect if you are not connected. That results in a major UX issue in case any app wants to call this method to update addresses in the background, which results in constantly opening wallet, when it's technically not required. This param allows optionally calling readOnly version of that method, without breaking existing connection logic anywhere else.
> feat(ux): add readOnly optional param to unisat getAddresses method

- packages/sdk/package.json
- packages/sdk/src/browser-wallets/metamask/signatures.ts
- packages/sdk/src/signatures/message.ts
- packages/sdk/src/wallet/Ordit.ts
- pnpm-lock.yaml
This PR installs & integrates [bip322-js](https://github.com/ACken2/bip322-js) lib to sign and verify messages generated using `p2wpkh`, `p2sh-p2wpkh`, and single-key-spend `p2tr` addresses.
[bitcoinjs-message](https://github.com/bitcoinjs/bitcoinjs-message) only supports `p2pkh` and despite their latest support to segwit, we would like to keep the segregation of libs that are capable to handle and well-designed for a specific purpose.
[BIP-322](https://github.com/bitcoin/bips/blob/master/bip-0322.mediawiki) outlines the approach bip322-js follows to enable message signing and verification for non-legacy addresses.
> feat(sdk): integrate bip322-js to sign & verify non-legacy address messages

- packages/sdk/src/browser-wallets/types.ts
- packages/sdk/src/browser-wallets/unisat/signatures.ts
- packages/sdk/src/types.d.ts
This PR extends the Unisat message signer to accept signature type. 
With the latest addition of `bip322` in #91 to enable message signing and verification for non-legacy addresses, signature verification would fail because Unisat generates `ecdsa` signatures and verification in Ordit-SDK is done using bip322-js (for non-legacy signatures) which uses [bip322 strategy](https://bips.xyz/322).
> feat(unisat): extend message signer to accept type

- packages/sdk/src/wallet/Ordit.ts
Currently, the `Ordit.signMessage` method signs message w/ the keypair corresponding to the selected address type. This PR improves that by letting the SDK consumer sign message w/ a different address type and keypair w\ having the consumer to `setDefaultAddress(x)` / switch to a different type.
> refactor(sdk): accept address type to sign message to override default

- packages/sdk/src/transactions/Inscriber.ts
Fix output amount being negative/0 or lower than dust amount bypassing the `isReady()` check when trying to use `recovery`
Note: `transaction.build()` will still fail, but at least this prevents `isReady` from being set to true
Fixes #
> fix(inscriber): ensure output is higher than dust

- packages/sdk/src/inscription/collection.ts
add `minter` to inscription metadata to ensure that generated address hash is always unique
Fixes #
> feat(sdk): add minter to inscription metadata

- packages/sdk/src/api/index.ts
- packages/sdk/src/api/jsonrpc.ts
- packages/sdk/src/api/types.ts
- packages/sdk/src/index.ts
- packages/sdk/src/inscription/types.ts
- packages/sdk/src/modules/BaseDatasource.ts
- packages/sdk/src/modules/JsonRpcDatasource.ts
- packages/sdk/src/modules/index.ts
- packages/sdk/src/transactions/Inscriber.ts
- packages/sdk/src/transactions/index.ts
- packages/sdk/src/transactions/types.ts
- packages/sdk/src/utxos/index.ts
1. export more typing
2. add `GetTransactions` RPC
3. update `GetInscriptions` RPC to include `includePostage` params
Fixes #
> feat(sdk): add GetTransactions + export more types

- examples/node/inscribeV2.js
- examples/node/package.json
- packages/sdk/src/inscription/collection.ts
- packages/sdk/src/inscription/encoding.ts
- packages/sdk/src/inscription/meta.ts
- packages/sdk/src/inscription/types.ts
- packages/sdk/src/inscription/witness.ts
- packages/sdk/src/transactions/InscriberV2.ts
- packages/sdk/src/transactions/index.ts
- packages/sdk/src/transactions/types.ts
- packages/sdk/src/utils/index.ts
Deprecate `Inscriber` class and use `InscriberV2` to support bulk minting as well.
Created `bulkMintFromCollection` function to build necessary params for InscriberV2
also to note that, on the scripting side due to [BIP-0062](https://github.com/bitcoin/bips/blob/master/bip-0062.mediawiki) bitcoinjs will try to convert scripts to its smallest possible push operation so `OP_PUSHBYTES_1 01` is the same as `OP_PUSHNUM_1`. This has also been supported by ord [PR](https://github.com/ordinals/ord/pull/2497)
Fixes #
> feat(sdk): support bulk minting with pointers

- packages/sdk/src/transactions/InscriberV2.ts
- packages/sdk/src/wallet/Ordit.ts
1. add tx size standardness check to enforce max 400,000 WU that is max tx that will be accepted by bitcoin core.
2. make `setDefaultAddress` second param as optional to make it backward compatible
Fixes #
> feat(sdk): Add max transaction size check

- packages/sdk/src/addresses/formats.ts
- packages/sdk/src/fee/FeeEstimator.ts
- packages/sdk/src/utils/constants.ts
- packages/sdk/src/utils/index.ts
PR is to support creating outputs to p2wsh addresses.
Native segwit estimate is taken off https://medium.com/coinmonks/on-bitcoin-transaction-sizes-part-2-9445373d17f4
Fixes #
> feat(SDK): support p2wsh format

- packages/sdk/src/utils/index.ts
> fix(sdk): split check for empty string

- packages/sdk/src/addresses/index.ts
- packages/sdk/src/api/jsonrpc.ts
- packages/sdk/src/config/index.ts
- packages/sdk/src/config/types.ts
- packages/sdk/src/fee/FeeEstimator.ts
- packages/sdk/src/fee/types.ts
- packages/sdk/src/inscription/collection.ts
- packages/sdk/src/instant-trade/InstantTradeBuilder.ts
- packages/sdk/src/instant-trade/InstantTradeBuyerTxBuilder.ts
- packages/sdk/src/instant-trade/InstantTradeSellerTxBuilder.ts
- packages/sdk/src/modules/BaseDatasource.ts
- packages/sdk/src/modules/JsonRpcDatasource.ts
- packages/sdk/src/transactions/Inscriber.ts
- packages/sdk/src/transactions/InscriberV2.ts
- packages/sdk/src/transactions/PSBTBuilder.ts
- packages/sdk/src/utils/index.ts
- packages/sdk/src/utxos/UTXOManager.ts
- packages/sdk/src/utxos/types.ts
- packages/sdk/src/wallet/Ordit.ts
Fractal bitcoin PSBTs are built with mainnet addresses, regardless of mainnet/testnet.
This PR updates Ordit to take in optional `chain` parameter to determine the network for building PSBT
Fixes #
> feat(sdk): account for fractal network
